version: "2"
services:
  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
    links:
      - app

  app:
    image: node:8.9.3-alpine
    container_name: node_express
    volumes:
      - ".:/src"
    working_dir: /src
    command: [sh, -c, npm install && npm start]
    #コンテナのポート3000をホストのポート3000で公開する
    ports:
      - "3000:3000"
